name: synpred-env  
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10    - pip
  - numpy==1.24.0
  - scikit-learn==1.2.0
  - pandas==2.0.0
  - matplotlib==3.7.0
  - tqdm==4.65.0

  - pytorch==2.0.0 torchvision==0.15.0 pytorch-cuda=11.8  
  - pip
  - pip:
      - torch-geometric==2.3.0
      - torchamp==0.2.0